In [ ]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, StandardScaler, MaxAbsScaler
from sklearn.model_selection import train_test_split

#  dataset loding
my_data = pd.read_csv('/content/dataset (1) (1).csv')
print(my_data.info())
print(my_data.head())

# making categorical variable
label_encoders = {}
categorical_columns = ['Income_type', 'Education_type', 'Family_status', 'Housing_type', 'Occupation_type']
for column in categorical_columns:
    label = LabelEncoder()
    my_data[column] = label.fit_transform(my_data[column])
    label_encoders[column] = label

# Preparing model
X = my_data.drop(columns=['ID', 'Target'])
y = my_data['Target']

# Splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=20)

# Scaling data
scaler_data =MaxAbsScaler()
X_train_scaled = scaler_data.fit_transform(X_train)
X_test_scaled = scaler_data.transform(X_test)

#  Regression classification
model = LogisticRegression(max_iter=1000)  # Increased max_iter for better convergence
model.fit(X_train_scaled, y_train)

# predictions
y_prediction = model.predict(X_test_scaled)

# Evaluating the model
accuracy1 = accuracy_score(y_test, y_prediction)
confusion_matrix = confusion_matrix(y_test, y_prediction)

# Printing results
print(f"Accuracy: {accuracy1*100:.2f}%")
print("Confusion Matrix:")
print(confusion_matrix)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9709 entries, 0 to 9708
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               9709 non-null   int64
 1   Gender           9709 non-null   int64
 2   Own_car          9709 non-null   int64
 3   Own_property     9709 non-null   int64
 4   Work_phone       9709 non-null   int64
 5   Phone            9709 non-null   int64
 6   Email            9709 non-null   int64
 7   Unemployed       9709 non-null   int64
 8   Num_children     9709 non-null   int64
 9   Num_family       9709 non-null   int64
 10  Account_length   9709 non-null   int64
 11  Total_income     9709 non-null   float64
 12  Age              9709 non-null   float64
 13  Years_employed   9709 non-null   float64
 14  Income_type      9709 non-null   object
 15  Education_type   9709 non-null   object
 16  Family_status    9709 non-null   object
 17  Housing_type     9709 non-null   object
 18  Occupation_type  9709 non-null   object
 19  Target           9709 non-null   int64
dtypes: float64(3), int64(12), object(5)
memory usage: 1.5+ MB
None
        ID  Gender  Own_car  Own_property  Work_phone  Phone  Email  \
0  5008804       1        1             1           1      0      0
1  5008806       1        1             1           0      0      0
2  5008808       0        0             1           0      1      1
3  5008812       0        0             1           0      0      0
4  5008815       1        1             1           1      1      1

   Unemployed  Num_children  Num_family  Account_length  Total_income  \
0           0             0           2              15      427500.0
1           0             0           2              29      112500.0
2           0             0           1               4      270000.0
3           1             0           1              20      283500.0
4           0             0           2               5      270000.0

         Age  Years_employed           Income_type  \
0  32.868574       12.435574               Working
1  58.793815        3.104787               Working
2  52.321403        8.353354  Commercial associate
3  61.504343        0.000000             Pensioner
4  46.193967        2.105450               Working

                  Education_type         Family_status       Housing_type  \
0               Higher education        Civil marriage   Rented apartment
1  Secondary / secondary special               Married  House / apartment
2  Secondary / secondary special  Single / not married  House / apartment
3               Higher education             Separated  House / apartment
4               Higher education               Married  House / apartment

  Occupation_type  Target
0           Other       1
1  Security staff       0
2     Sales staff       0
3           Other       0
4     Accountants       0
Accuracy: 86.46%
Confusion Matrix:
[[1679    0]
 [ 263    0]]